### ISSUE TITLE
Main Example - Schema Validation doesn't match DSL

### ISSUE THREAD

**Issue by tmarrs** [nicolasdespres/respect#16]
The DSL now looks like this:

schema = Respect::HashSchema.define do |s|
  s.string "name"
  s.integer "age", greater_than: 18
  s.string "homepage", format: :uri
end

But the schema validation will always be false:
schema.validate?({ "name" => "My name", "age" => 20, "email" => "me@example.com" })
schema.validate?({ "name" => "My name", "age" => 15, "email" => "me@example.com" })

The last parameter/key is "email", and it should be "homepage" to match the DSL. Of course, you'll need an appropriate URI value to go with it.

**Comment by nicolasdespres** [comment]
Very sorry I got confused when (too) quickly fixing your previous issue because I though I had changed my mind while writing the example. I have re-read all the "Take a tour" section of the README file so now I hope there is no more mistakes. I hope you got the idea of the project anyway. Thanks again.

**Comment by tmarrs** [comment]
That's OK - it works properly now. The DSL and validation work as advertised.
You've done an excellent job on this project.

**Comment by nicolasdespres** [comment]
Glade to read that. Thanks! :-)
